/*
 * memory_eeprom.h
 */

#ifndef MEMORY_EEPROM_H_
#define MEMORY_EEPROM_H_

#ifdef __cplusplus
 extern "C" {
#endif

#include "m95m01_eeprom.h"

// physical defines
#define	EEP_MEMORY_SIZE				131072UL						// 128 KByte eeprom size
#define EEP_PAGE_SIZE				256UL

#define EEP_STATUS_SIZE				(8UL * EEP_PAGE_SIZE)			// 2048 bytes
#define EEP_BLACKBOX_SIZE			(2UL * EEP_PAGE_SIZE)			// 512 bytes
#define EEP_BLOCKTABLE_SIZE			(128UL * EEP_PAGE_SIZE)			// 32768 bytes
#define EEP_CALIBRATION_SIZE		(128UL * EEP_PAGE_SIZE)			// 32768 bytes
#define EEP_CYCLOGRAM_SIZE			(128UL * EEP_PAGE_SIZE)			// 32768 bytes
#define EEP_SCENARIO_SIZE			(118UL * EEP_PAGE_SIZE)			// 30208 bytes

#define EEP_STATUS_ADDRESS			0
#define EEP_BLACKBOX_ADDRESS		(EEP_STATUS_SIZE)
#define EEP_BLOCKTABLE_ADDRESS 		(EEP_BLACKBOX_ADDRESS + EEP_BLACKBOX_SIZE)
#define EEP_CALIBRATION_ADDRESS		(EEP_BLOCKTABLE_ADDRESS + EEP_BLOCKTABLE_SIZE)
#define EEP_CYCLOGRAM_ADDRESS		(EEP_CALIBRATION_ADDRESS + EEP_CALIBRATION_SIZE)
#define EEP_SCENARIO_ADDRESS		(EEP_CYCLOGRAM_ADDRESS + EEP_CYCLOGRAM_SIZE)

// STATUS (8 pages)
#define	EEP_START_STATUS_ADDRESS	(EEP_STATUS_ADDRESS + EEP_PAGE_SIZE * 0)
#define	EEP_BLACKOUT_LOG_ADDRESS	(EEP_STATUS_ADDRESS + EEP_PAGE_SIZE * 1)
#define EEP_START_TIME_ADDRESS		(EEP_STATUS_ADDRESS + EEP_PAGE_SIZE * 2)
#define EEP_BOOTFLAG_ADDRESS		(EEP_STATUS_ADDRESS + EEP_PAGE_SIZE * 3)

#define	EEP_START_STATUS_SIZE		EEP_PAGE_SIZE
#define	EEP_BLACKOUT_LOG_SIZE		EEP_PAGE_SIZE
#define	EEP_START_TIME_SIZE			EEP_PAGE_SIZE
#define	EEP_BOOTFLAG_SIZE			EEP_PAGE_SIZE

// BLACKBOX (2 pages)
#define EEP_BLACKBOX_1_ADDRESS		(EEP_BLACKBOX_ADDRESS)
#define EEP_BLACKBOX_2_ADDRESS		(EEP_BLACKBOX_ADDRESS + EEP_PAGE_SIZE)

#ifdef __cplusplus
}
#endif

#endif /* MEMORY_EEPROM_H_ */
